### ISSUE TITLE
Can we migrate `config.js` to `config.json` ?

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-online#144]
A `config.js` script file is generated as a pre-requisite just prior to the nginx webserver being executed in the docker image. The config.js contains the following (with the shell variables evaluated):
```
window.OPENSHIFT_CONFIG = {
  master_uri: new URI().query('').path('/master').toString(),
  hawtio: {
    mode: '${HAWTIO_ONLINE_MODE}'
  },
  openshift: {
    oauth_metadata_uri: new URI().query('').path('/master/.well-known/oauth-authorization-server').toString(),
    oauth_client_id: '${HAWTIO_OAUTH_CLIENT_ID:-hawtio-online}',
    scope: 'user:info user:check-access user:list-projects role:edit:*',
    web_console_url: '${OPENSHIFT_WEB_CONSOLE_URL:-}',
    cluster_version: '${OPENSHIFT_CLUSTER_VERSION:-}'
  }
};
```

This script is then served by the webserver on a path of `http://localhost/osconsole/config.js`.

The hawtio-online app, as part of the kubernetes-api, [reads](https://github.com/hawtio/hawtio-kubernetes-api/blob/main/plugins/kubernetes-api/kubernetes-api.module.ts#L61) this file using `$.getScript()`.

Concerns with this approach:

1. Is this a potential vulnerability that could lead to arbitrary code execution?
2. The `$.getScript()` function has a deficiency. In development, the `osconsole/config.js` url has not yet been configured in the testing `devServer` hence, rather than a 404 error, the html of the development server is being returned (html not javascript). Despite an error being thrown in the console, ie. `Uncaught SyntaxError: Unexpected token '<'`, the promise's `fail()` function is not executed but the `done()` function. This appears to be a known problem (see [here](https://github.com/jquery/jquery/issues/4655));
3. Since the contents of `config.js` is essentially data, would it not be better to have this file be generated as json then use a `get` or `fetch` function to retrieve and read it. The resulting object could then be dealt with in a similar manner and not require `window. ....` to be specified. If this causes an issue with some other component of the image then, seeing as the `config.js` is generated via a `config.sh` bash script, we could extend that script to create both the js and json files. That way the json version is safely read?

Thoughts?

**Comment by tadayosi** [comment]
> 1. Is this a potential vulnerability that could lead to arbitrary code execution?

Yes, we should not rely on `$.getScript()`. Also, we should not use jQuery features as much as possible. https://github.com/hawtio/hawtio-next/issues/76
That's part of the reasons why our plugin mechanism moved from `$.getScript()` to Webpack Module Federation.

> 2. The `$.getScript()` function has a deficiency. In development, the `osconsole/config.js` url has not yet been configured in the testing `devServer` hence, rather than a 404 error, the html of the development server is being returned (html not javascript). Despite an error being thrown in the console, ie. `Uncaught SyntaxError: Unexpected token '<'`, the promise's `fail()` function is not executed but the `done()` function. This appears to be a known problem (see [here](https://github.com/jquery/jquery/issues/4655));

I don't think it's a deficiency in `$.getScript()`. The error is expected except that the error message tells little hint on what's really happened. For the dev server, we should define extra resources other than `index.html` ourselves like this: https://github.com/hawtio/hawtio-next/blob/main/app/craco.config.js#L137-L145
What you'd need is just add the get entry for `/osconsole/config.js` to the dev server and return whatever you like for testing.

> 3. Since the contents of `config.js` is essentially data, would it not be better to have this file be generated as json then use a `get` or `fetch` function to retrieve and read it. The resulting object could then be dealt with in a similar manner and not require `window. ....` to be specified. If this causes an issue with some other component of the image then, seeing as the `config.js` is generated via a `config.sh` bash script, we could extend that script to create both the js and json files. That way the json version is safely read?

Yes, I think it's good idea to convert it to `config.json`. Let's use [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead of jQuery then. I think the only consideration then is how we can pre-encode the dynamically generated URIs:
```
  master_uri: new URI().query('').path('/master').toString(),
  ...
    oauth_metadata_uri: new URI().query('').path('/master/.well-known/oauth-authorization-server').toString(),
```
but I wonder why we couldn't just receive json like the following:
```
  master_uri: '/master',
  ...
    oauth_metadata_uri: '/master/.well-known/oauth-authorization-server',
```
and prepend `location.href` after loading the json.

@astefanutti Could you give us input on the last part?  Do you remember why `config.js` was used instead of `config.json`?  Do you think it's feasible to convert to simple JSON?

**Comment by tadayosi** [comment]
> 3. Since the contents of `config.js` is essentially data, would it not be better to have this file be generated as json then use a `get` or `fetch` function to retrieve and read it. The resulting object could then be dealt with in a similar manner and not require `window. ....` to be specified. If this causes an issue with some other component of the image then, seeing as the `config.js` is generated via a `config.sh` bash script, we could extend that script to create both the js and json files. That way the json version is safely read?

Yes, I think it's good idea to convert it to `config.json`. Let's use [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead of jQuery then. I think the only consideration then is how we can pre-encode the dynamically generated URIs:
```
  master_uri: new URI().query('').path('/master').toString(),
  ...
    oauth_metadata_uri: new URI().query('').path('/master/.well-known/oauth-authorization-server').toString(),
```
but I wonder why we couldn't just receive json like the following:
```
  master_uri: '/master',
  ...
    oauth_metadata_uri: '/master/.well-known/oauth-authorization-server',
```
and prepend `location.href` after loading the json.

@astefanutti Could you give us input on the last part?  Do you remember why `config.js` was used instead of `config.json`?  Do you think it's feasible to convert to simple JSON?

**Comment by phantomjinx** [comment]
I think the `location.href` would be insufficient since it limits the host address to the host currently executing hawtio-online. This is fine for production but makes it less appealing for development. Since we have a `config.sh` script anyway then when it is executed to generate the `config.json`, it injects the correct urls fully-formed. Will add the `config.sh` to development to so that this approach can be tested.

**Comment by tadayosi** [comment]
> Since we have a `config.sh` script anyway then when it is executed to generate the `config.json`, it injects the correct urls fully-formed.

I don't think this works. It's because `config.sh` is currently run when the pod starts the hawtio-online container, but the real fully-formed urls are decided when the service, route, or ingress is created for the pod, which can occur after the pod is started. That's why the old hawtio-online needed to attach `location.href` (note `new URI()` is effectively just `location.href`) at client side.

For development, I think we can follow the same way as https://github.com/hawtio/hawtio-online#development, so the location should be `localhost`. I don't see why `location.href` doesn't work for development.

**Comment by phantomjinx** [comment]
Now caught up how development keeps to `localhost` using a proxy config to target the cluster master uri to `/master`. So putting this into practice.

**Comment by phantomjinx** [comment]
Need to leave this open so that when we come to production and release, we remember to migrate the existing `config.js` to `config.json` in the docker image.

**Comment by phantomjinx** [comment]
Migration to `config.json` in all code bases is now complete.
