### ISSUE TITLE
Hawtio Online lists any pod having a port named jolokia, even if it's not serving jolokia resources

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-online#342]
I used quay.io/fuse_qe/http-https-echo image with the 8443 port named jolokia and hawtio-online makes requests to it, and even though it's not returning any jolokia responses it gets listed in the UI, but when you click on the connect button, it leads to a blank page.

**Comment by tadayosi** [comment]
@mmuzikar I think because that's the only (lightweight) way Hawtio Online can know whether a pod provides a Jolokia endpoint or not. I wonder why a pod names a port `jolokia` but without intention to provide a real Jolokia endpoint?

**Comment by mmuzikar** [comment]
It's definitely an edge case, I was thinking if it's possible to check the response if the response is jolokia based resource.

**Comment by phantomjinx** [comment]
I would say this has now been fixed.

Although the pod **is** listed since a port has been named `jolokia` it cannot be connected to since the probing of the port returns the error of unrecognized. This makes sense to me because: 
- the deployment actually names a port, not configured as jolokia, **to be** jolokia so deserves to be listed;
- the probing of the port fails to be recognized so nothing more can be done with it

![Screenshot_20240322_132718](https://github.com/hawtio/hawtio-online/assets/1634180/0a552925-07ab-4459-b984-eeae529410bf)
