### ISSUE TITLE
kubectl apply -k deploy/k8s/cluster/ Is not working

### ISSUE THREAD

**Issue by kdb3001** [hawtio/hawtio-online#458]
Hello,

We are trying to set up hawtio-online application on the Kubernetes.

we have followed the readme document.

But when we run the  **kubectl apply -k deploy/k8s/cluster/** command we are getting below error -

**ERROR -**

error: accumulating resources: accumulation err='accumulating resources from '../../base': '/ext/aws89/hawtiosource-2.0/hawtio-online-2.0.0/deploy/base' must resolve to a file': recursed accumulation of path '/ext/aws89/hawtiosource-2.0/hawtio-online-2.0.0/deploy/base': trouble configuring builtin PatchTransformer with config: `
path: ../patches/patch-hawtconfig-configmap.yml
target:
  kind: Deployment
`: security; file '/ext/aws89/hawtiosource-2.0/hawtio-online-2.0.0/deploy/patches/patch-hawtconfig-configmap.yml' is not in or below '/ext/aws89/hawtiosource-2.0/hawtio-online-2.0.0/deploy/base'

Kindly suggest if we are missing something

**Comment by phantomjinx** [comment]
` security; file '/ext/aws89/hawtiosource-2.0/hawtio-online-2.0.0/deploy/patches/patch-hawtconfig-configmap.yml' is not in or below '/ext/aws89/hawtiosource-2.0/hawtio-online-2.0.0/deploy/base'`

Kustomize has the default security limitation of stopping resource files from outside the current directory from being included. In this case, the `patch-hawtconfig-configmap.yml` is in the `patches` directory.

This can be avoided by using `kustomize --load-restrictor LoadRestrictionsNone` rather than `kubectl -k`. The documentation needs to be updated to reflect this change. If preferred, `make` can be used instead along with the [deploy/Makefile](https://github.com/hawtio/hawtio-online/blob/main/deploy/Makefile).

`make help` describes the rules that can be called and the respective parameters. In the case of an install on Kubernetes then the following might work for you:

`CLUSTER_TYPE=k8s MODE=cluster NAMESPACE=<your namespace> make install`
