### ISSUE TITLE
Local run doesn't work with OpenShift 4.x

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#59]
In development, when running hawtio-online locally it shows pods that are running on OpenShift 4.x, but connecting to one of them it gets "Connection lost" errors in a new window and fails.
https://github.com/hawtio/hawtio-online#run

**Comment by tadayosi** [comment]
Adding the following env vars to the app deployments makes external `curl` to the Jolokia endpoints work, but still local hawtio-online doesn't work.
```
AB_JOLOKIA_AUTH_OPENSHIFT=false
AB_JOLOKIA_PASSWORD_RANDOM=false
AB_JOLOKIA_OPTS=useSslClientAuthentication=false,protocol=https
```

**Comment by astefanutti** [comment]
It's broken because of https://github.com/hawtio/hawtio-online/commit/752be3fe86df842a862a207aba28375534371f30.

For it to work, the local reverse proxy configuration must be updated, so that it rewrites the requests made to the `management` path:

https://github.com/hawtio/hawtio-online/blob/8c546f23f1ad6ccfe8fb09273778ad957581c7b0/gulpfile.js#L86

**Comment by tadayosi** [comment]
Hi @astefanutti, fyi just reverting https://github.com/hawtio/hawtio-online/commit/752be3fe86df842a862a207aba28375534371f30 doesn't resolve the issue for me. There appears to be other places that still invokes `/management/namespaces/...` paths.

**Comment by astefanutti** [comment]
@tadayosi ah right, there is also https://github.com/hawtio/hawtio-online/blob/8c546f23f1ad6ccfe8fb09273778ad957581c7b0/packages/online/src/discover/discover.module.ts#L77
Better fixing the reverse proxying anyway 😉.
