### ISSUE TITLE
Proxying apiserver request allows eaves dropping of client bearer tokens

### ISSUE THREAD

**Issue by vinzent** [hawtio/hawtio-online#60]
Reading [nginx-gateway.conf](https://github.com/hawtio/hawtio-online/blob/master/docker/nginx-gateway.conf) I understand that apiserver communication is routed this way: user -> browser -> hawtio-online nginx proxy -> kube-apiserver

Proxying of apiserver requests enables a deployer of hawtio-online (or Fuse Console 7.x) to eaves drop any apiserver bearer token. 

You just need some user with more privileges than you (think of:  cluster-admin) to login to your hawtio-online console. If you prepared to log the header you now are able to do requests as that user.

Why is it technically required to proxy the apiserver requests? 

Why can't the browser app connect directly to the apiserver instead?

**Comment by astefanutti** [comment]
Not proxying the API server would require to configure CORS, so that Web browsers do not block request to it. While it is possible to add allowed origins using the `--cors-allowed-origins` option from the API server CLI, that requires to pre-configure the cluster API server.

When the users connect to the console, the console certificate, typically issued by the cluster service signing certificate operator, on behalf of the _deployer_, has to be trusted. You're right that once trust is given, a malicious _deployer_ could intercept bearer tokens and use them to impersonate users.

Note that client bearer tokens are scoped tokens. For the _cluster_ mode, the `user:info user:check-access user:list-projects role:edit:*` scope is requested. The console is almost read-only (`edit` is only used to check RBAC), so we may be able to offer a hardened setup, where scope tokens do not grant _write_ operations on the API server.

**Comment by vinzent** [comment]
Thanks @astefanutti providing these insights! Good to know that the token is scoped ([also probably found config source for that (config.sh)](https://github.com/hawtio/hawtio-online/blob/f20a8ebe8da733cc6bc9f1abcbcdf3c88036b245/docker/osconsole/config.sh#L13)). Still the edit role is something like a "namespace admin" (at least for the more restrictive/regulated environments). As you wrote, it seems it is technically required to proxy the request as changing the apiserver params doesn't seem like a doable thing. So the hardened setup without write privileges seems to be a desirable thing to me.

Reading [Delegate authentication and authorization to OpenShift for infrastructure (openshift/oauth-proxy)](https://github.com/openshift/oauth-proxy/#delegate-authentication-and-authorization-to-openshift-for-infrastructure) :

> WARNING: Because users are sending their own credentials to the proxy, it's important to use this setting 
> only when the proxy is under control of the cluster administrators. Otherwise, end users may be unwittingly 
> provide their credentials to untrusted components that can then act as them.

Does that warning apply to the hawtio-online way of using bearer tokens?

**Comment by astefanutti** [comment]
@vinzent, indeed, the warning from _oauth-proxy_ applies to hawtio-online. In _cluster_ mode, the console has to be set up by a cluster admin, that has access to the service signing certificate private key. So that mitigate the issue. Still your point is important and it'd be worth mentioning it in the documentation.

**Comment by vinzent** [comment]
I think the console not only needs to be setup by a cluster-admin also it is required to stay under control by the cluster-admin. The only thing that requires cluster-admin prermissions by default is the creation of the OAuthClient resource. Once this resource is created anybody with edit role in the namespace can adjust requested token scopes and the nginx config.

Having this as a hint in the docs would be good to create awareness about this risk.

**Comment by astefanutti** [comment]
Yes, in a typical deployment in _cluster_ mode, the console should be deployed by an administrator, in a lock-down namespace, that any other users are not granted permission to access at all. I agree we should document that canonical deployment and the rational behind it.
